language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

install:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then
    curl -LS https://pecl.php.net/get/event | tar -xz;
    pushd event-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=event.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    curl -LS https://pecl.php.net/get/libevent | tar -xz;
    pushd libevent-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=libevent.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    curl -LS https://pecl.php.net/get/ev | tar -xz;
    pushd ev-*;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=ev.so" >> "$(php -r 'echo php_ini_loaded_file();')";
    fi
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
